---
title: "Tabelas Danilo"
author: "Gabriel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#GO Down
```{r}
danilo_go_down <- read.xlsx("Tabelas Danilo/Resultados GO genes DOWN_final.xlsx")

danilo_go_down <- danilo_go_down %>% rename("category" = "ONTOLOGY", "term" = "Description", "genes" = "geneID", "adj_pval" = "p.adjust")
danilo_go_down$genes <-  gsub("/", ", ", danilo_go_down$genes)

circ_dan_down <- circle_dat(danilo_go_down, res.down_goplot)
pdf("Tabelas Danilo/Bubbleplot_down_selecionados.pdf", width = 10, height = 8)
GOBubble(circ_dan_down, labels = 2.5, table.col = F)
dev.off()
```

```{r}
danilo_go_up <- read.xlsx("Tabelas Danilo/Resultados GO genes up_final.xlsx")

danilo_go_up <- danilo_go_up %>% rename("category" = "ONTOLOGY", "term" = "Description", "genes" = "geneID", "adj_pval" = "p.adjust")
danilo_go_up$genes <-  gsub("/", ", ", danilo_go_up$genes)

circ_dan_up <- circle_dat(danilo_go_up, res.up_goplot)

pdf("Tabelas Danilo/Bubbleplot_up_selecionados.pdf", width = 10, height = 8)
GOBubble(circ_dan_up, labels = 2, table.col = F)
dev.off()
```

#KEGG treeplot
```{r}
pdf("Tabelas Danilo/Treeplot_KEGG.pdf", width = 16, height = 8)
treeplot(pairwise_termsim(KEGG))
dev.off()
```

#GO all
```{r}
go_all_danilo <- read.xlsx("Tabelas Danilo/Resultados GO genes_all_final.xlsx")
danilo_classes <- read.xlsx("Tabelas Danilo/Resultados GO genes_all_final.xlsx", sheet=3)
danilo_ang <- filter(danilo_classes, Classe == "ang")
danilo_diff <- filter(danilo_classes, Classe == "diff")

#Full
pdf("Tabelas Danilo/Circleplot_Vascular_Function_and_Angiogenesis_FULL.pdf", width = 16, height = 10)
GOCircle(circ_all, nsub=danilo_ang$Termo, label.size = 3)
dev.off()


pdf("Tabelas Danilo/Circleplot_Stromal_and_Differentiation_FULL.pdf", width = 16, height = 10)
GOCircle(circ_all, nsub=danilo_diff$Termo, label.size = 4)
dev.off()

danilo_ang

#Mais intensos
pdf("Tabelas Danilo/Circleplot_Vascular_Function_and_Angiogenesis_SELECTED.pdf", width = 12, height = 10)
GOCircle(circ_all, nsub=danilo_ang$Termo[c(9,16,17,18,22, 4, 12, 13)])
dev.off()

pdf("Tabelas Danilo/Circleplot_Stromal_and_Differentiation_SELECTED.pdf", width = 12, height = 10)
GOCircle(circ_all, nsub=danilo_diff$Termo[c(1,2,3,5,6)])
dev.off()
```

#Interseção genes
```{r}
angio.genes2 <- angio.genes %>% dplyr::rename(genes=Genes)
#angio.genes é o hallmark_angiogenesis

danilo_ang

circ_all %>% filter(term %in% danilo_ang$Termo[12]) %>% dplyr::select(genes) %>% dplyr::intersect(., as.data.frame(angio.genes2))

# [4], [12], [13] STC1

danilo_ang[c(4,12,13),]
```


```{r}
venn <- list(
  `End.cel.mig` = c(circ_all %>% filter(term %in% danilo_ang$Termo[4]) %>% dplyr::select(genes)),
  `Reg.end.cel.mig` = c(circ_all %>% filter(term %in% danilo_ang$Termo[12]) %>% dplyr::select(genes)),
  `Reg.blood.circ` = c(circ_all %>% filter(term %in% danilo_ang$Termo[13]) %>% dplyr::select(genes)),
  `Hallmark_angio` = angio.genes2)

venn.list <- list(`Endothelial cell migration` = c(venn$End.cel.mig$genes),
                    `Reg. of endothelial cell migration` = c(venn$Reg.end.cel.mig$genes),
                    `Reg. of blood circulation` = c(venn$Reg.blood.circ$genes),
                  `Hallmark angiogenesis` = venn$Hallmark_angio$genes)

list(venn[[1]])
list(venn)
venn[2]
intersect(venn[1], venn[2])

VennDiagram::venn.diagram(list(venn[1], venn[2], venn[3]),
                          filename = "Venn diagram.png",
                          category.names = c("1", "2", "3"),
                          outcome=T)

install.packages("ggvenn")              
library(ggvenn)

teste <- list(A=c("Teste", "STC1", "RPG", "ABROBA"),
              B=c("Azucar", "Tempero", "ABROBA", "STC1", "Relogio", "Trator"))


pdf("Venn_termos enriquecimento.pdf", width = 12, height = 8)
ggvenn(venn.list,
       show_elements = F, 
       text_size = 3.5,
       show_percentage = F, 
       set_name_size = 6,
       fill_color = c("#31688EFF", "#35B779FF", "#FB9A06FF", "#FCFFA4FF"),
       set_name_color = c("#31688EFF", "#35B779FF", "#ED6925FF", "black"))+
  geom_tile(aes(x=0, y=-.7, width=.4, height=.2), alpha=.2, fill="#FCFFA4FF", color="orange")+
  annotate(geom="text", label="STC1", size=6, x=0, y=-.7)+
  coord_cartesian(expand = T, xlim=c(-2.5,2.5))
dev.off()

       
"#440154FF" "#482878FF" "#3E4A89FF" "#31688EFF" "#26828EFF" "#1F9E89FF" "#35B779FF" "#6DCD59FF" "#B4DE2CFF" "#FDE725FF"
       
       "#000004FF" "#1B0C42FF" "#4B0C6BFF" "#781C6DFF" "#A52C60FF" "#CF4446FF" "#ED6925FF" "#FB9A06FF" "#F7D03CFF" "#FCFFA4FF"
```


#Circplot Final
```{r}
diff_vfinal <- c("GO:0003417", "GO:0048762", "GO:0042476", "GO:0072132", "GO:0001503")
ang_vfinal <- c("GO:0001569", "GO:0001938", "GO:0003018", "GO:0097746", "GO:0001935", "GO:2000181")

(go_all_danilo %>% filter(ID %in% diff_vfinal))$term

pdf("Tabelas Danilo/Circleplot_Stromal_and_Differentiation_SELECTED_v2.pdf", width = 12, height = 10)
GOCircle(circ_all, nsub=(go_all_danilo %>% filter(ID %in% diff_vfinal))$term)
dev.off()

pdf("Tabelas Danilo/Circleplot_Vascular_Function_and_Angiogenesis_SELECTED_v2.pdf", width = 12, height = 10)
GOCircle(circ_all, nsub=(go_all_danilo %>% filter(ID %in% ang_vfinal))$term)
dev.off()
```

#Expressao gene
```{r}
exp_genes <- as.data.frame(exp_gse62_final) %>% rownames_to_column(var="PROBEID") %>% left_join(res_gse62_lfc, by="PROBEID")
STC1 <- filter(exp_genes, SYMBOL == "STC1")
STC1 <- STC1[,2:10]

STC1 <- melt(STC1)
STC1 <- left_join(STC1, pd[,c("geo_accession", "cell type:ch1")], by=c("variable"="geo_accession"))

STC1 %>% ggplot(aes(`cell type:ch1`, value, fill=`cell type:ch1`))+
  stat_summary(fun.data=mean_sd, geom="errorbar", width=.2)+
  stat_summary(fun=mean, geom="bar", width=.5)+
  
  theme_classic()+
  labs(x=NULL, y="STC1 normalized expression")+
  scale_fill_manual(values=c("blue", "yellow"), name="Cell type", labels=c("Mesenchymal", "Pericyte"))+
  coord_cartesian(expand=F, xlim=c(0.5, 2.5), ylim=c(0,12.5))+
  theme(axis.text = element_text(size=12, color="black"))+
  scale_x_discrete(labels=c("Mesenchymal", "Pericyte"))
  

STC1 %>% ggplot(aes(`cell type:ch1`, value, fill=`cell type:ch1`))+
  geom_violin(color=NA, trim=T)+
  theme_classic()+
  labs(x=NULL, y="STC1 normalized expression")+
  scale_fill_manual(values=c("blue", "yellow"), name="Cell type", labels=c("Mesenchymal", "Pericyte"))+
  coord_cartesian(expand=F, xlim=c(0.5, 2.5), ylim=c(0,12.5))+
  theme(axis.text = element_text(size=12, color="black"))+
  scale_x_discrete(labels=c("Mesenchymal", "Pericyte"))
```

